docs(login-bridge): add documentation for zapp login and zapp player
applicaster/React-Native-Zapp-Bridge pull request #15
Opened 2018-03-12 12:00 UTC by lukehaas

## Description
Add documentation for Zapp login methods and Zapp player methods being used in the new VideoDetail component.

## Known Issues:
### Checklist for this pull request
- [x] PR is scoped to one task
- [ ] Tests included
- One of:
- [x] The PR is not making any UI change
- [ ] The PR is making a UI change but not a product change
- [ ] Screenshots included

2018-03-12 13:14 UTC, francois-codes requested changes

2018-03-12 13:14 UTC, f-roland commented on README.md
> +`params: Object`
What are the available parameters ?

2018-03-12 13:27 UTC, francois-codes approved these changes

2018-03-12 13:27 UTC, lukehaas commented on README.md
> +`params: Object`
I've updated to make this clearer. In it's current use we're just sending an empty object, but it could be used to pass anything that's needed.

2018-03-12 13:30 UTC, f-roland commented on README.md
> +`params: Object`
Yeah I get it. It's just unnatural - when you have a login method, you expect to be able to send credentials and get a token back. But the problem is not in the documentation, it's in our architecture of the login feature. And that's a problem for another day unfortunately

2018-03-12 13:40 UTC, merged

2018-03-29 10:35 UTC, f-roland commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-zapp-bridge)
- [GitHub release](https://github.com/applicaster/React-Native-Zapp-Bridge/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: