DRSD-73 - fix - navigation from RN plugin works incorrect
applicaster/React-Native-Zapp-Bridge pull request #57
Opened 2019-12-03 11:34 UTC by ntolstikova

## Description:

## Known Issues:

### Checklist for this pull request

* [ ] PR is scoped to one task
* [ ] Tests are included
* [ ] Documentation included
* [ ] One of:
  * [ ] The PR is not making any UI change
  * [ ] The PR is making a UI change but not a product change
    * [ ] Screenshots included

Thank you!

2019-12-03 12:59 UTC, drorg commented
https://applicaster.atlassian.net/servicedesk/customer/portal/2/DRSD-73

2019-12-03 13:23 UTC, Budaa requested changes
1. Please read `Please Read before you contribute` readme section first. I can see that there is one commit that is not following the pattern. It's very important as our release mechanism is based on having correct commits. 
2. I'm fine with the feature, just please add a description of this behaviour to the README file.

2019-12-03 13:27 UTC, Budaa commented
It would as well be great to have a test if the function is indeed returning passed protocol, instead of doing a snapshot.

2019-12-03 14:30 UTC, ntolstikova commented
@Budaa There are necessary url ('SOME_PROTOCOL') in the snapshot. I think it's enough.

2019-12-03 14:40 UTC, ntolstikova commented
@Budaa Added tests and Readme description, please check it

2019-12-04 10:03 UTC, aethiss commented
i close this pr, we don't need this "fix"

2019-12-04 10:03 UTC, closed without merging